import Head from 'next/head'
import { userLoginAction } from '../redux/action/userAction'
import { wrapper } from '../redux/store'
import TodoComponent from '../component/Todo'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App with Redux (Boilerplate)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodoComponent />

    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps((store) => async ({ req }) => {
  await store.dispatch(userLoginAction(req))
})